import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { getOrderById, getOrderDelivery, type DeliveryPayload, formatMoney } from "@/lib/api";
import { SiteHeader, SiteFooter } from "@/components/site-header";
import { SupportPopups, SupportHelpSection } from "@/components/support-popups";
import { Clock, CheckCircle2, Truck, XCircle, ShieldCheck, ArrowLeft, Loader2, Copy, Eye, EyeOff } from "lucide-react";
import { toast } from "sonner";
import type { Order } from "@/lib/mock-data";

export const Route = createFileRoute("/order-status/$orderId")({ component: OrderStatusPage });
function OrderStatusPage() { const { orderId } = Route.useParams(); const { data: order, isLoading } = useQuery({ queryKey: ["order", orderId], queryFn: () => getOrderById(orderId), refetchInterval: 5000 }); return <div className="min-h-screen"><SiteHeader /><SupportPopups /><main className="mx-auto max-w-3xl px-4 py-12 sm:px-6"><Link to="/products" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back to products</Link><div className="mt-6 glass rounded-3xl p-8">{isLoading ? <div className="flex flex-col items-center py-10 text-muted-foreground"><Loader2 className="h-8 w-8 animate-spin" /><p className="mt-3 text-sm">Loading order…</p></div> : !order ? <div className="py-10 text-center"><h1 className="text-2xl font-bold">Order not found</h1><p className="mt-2 text-muted-foreground">We couldn't find order <span className="font-mono">{orderId}</span>.</p><Link to="/products" className="mt-6 inline-block rounded-xl bg-gradient-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground">Browse Products</Link></div> : <OrderDetailsWithDelivery order={order} />}</div></main><SiteFooter /></div>; }
function OrderDetailsWithDelivery({ order }: { order: Order }) { const { data: delivery } = useQuery({ queryKey: ["delivery", order.id], queryFn: () => getOrderDelivery(order.id), enabled: order.status === "approved" || order.status === "delivered", refetchInterval: false }); return <OrderDetails order={order} delivery={delivery ?? null} />; }
function OrderDetails({ order, delivery }: { order: Order; delivery?: DeliveryPayload | null }) { const meta = statusMeta(order.status); return <><div className="flex flex-col items-center text-center"><div className={`grid h-20 w-20 place-items-center rounded-full ${meta.iconBg}`}>{order.status === "pending" ? <div className="waiting-ring scale-75" /> : <meta.Icon className={`h-10 w-10 ${meta.iconColor}`} />}</div><h1 className="mt-5 text-3xl font-bold">{meta.title}</h1><p className="mt-2 max-w-md text-sm text-muted-foreground">{meta.message}</p><div className={`mt-5 inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-xs font-semibold ${meta.badge}`}><meta.Icon className="h-3.5 w-3.5" /> {meta.label}</div></div><div className="mt-6"><SupportHelpSection title="Need help with this order?" /></div><div className="mt-8 rounded-2xl border border-border bg-white/60 p-5 text-sm"><h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Order Details</h2><div className="mt-3 space-y-2"><Row label="Order ID" value={order.id} mono /><Row label="Product" value={order.productName} /><Row label="Amount" value={formatMoney(order.amount, order.currency)} /><Row label="Payment" value={`${order.paymentChannel} (${order.paymentMethod})`} /><Row label="Transaction ID" value={order.transactionId} mono />{order.customerOrderRef && <Row label="Your Reference" value={order.customerOrderRef} mono />}{order.approvedByNickname && <Row label="Approved by" value={order.approvedByNickname} />}{order.deliveredByNickname && <Row label="Delivered by" value={order.deliveredByNickname} />}<Row label="Placed" value={new Date(order.createdAt).toLocaleString()} /></div></div>{(order.status === "approved" || order.status === "delivered") && <DeliveryCard delivery={delivery} />}{order.status === "rejected" && <div className="mt-6 rounded-2xl border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive">Order rejected. Please contact support for assistance.</div>}</>; }
function DeliveryCard({ delivery }: { delivery?: DeliveryPayload | null }) { const [show, setShow] = useState(false); const password = delivery?.password || ""; return <div className="mt-6 rounded-3xl border border-success/30 bg-success/5 p-5"><div className="flex items-center gap-2 text-sm font-semibold text-success"><ShieldCheck className="h-4 w-4" /> Secure Delivery</div><p className="mt-2 text-sm text-muted-foreground">Keep this information private. Do not share your order link.</p>{delivery ? <div className="mt-5 space-y-4"><Info label="Login Email" value={delivery.email || ""} /><div className="rounded-2xl bg-white/70 p-4"><div className="text-xs font-semibold uppercase text-muted-foreground">Password</div><div className="mt-2 flex items-center justify-between gap-3"><span className="break-all font-mono text-lg font-bold text-slate-900">{show ? password : "•".repeat(Math.max(8, password.length || 8))}</span><div className="flex gap-2"><button type="button" onClick={() => setShow(!show)} className="rounded-lg bg-secondary px-2 py-1 text-xs">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button>{password && <CopyButton value={password} />}</div></div></div>{(delivery.instruction || delivery.instructions) && <div className="rounded-2xl bg-white/70 p-4"><div className="text-xs font-semibold uppercase text-muted-foreground">Instructions</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-800">{delivery.instruction || delivery.instructions}</p></div>}{delivery.videoUrl && <MediaVideo url={delivery.videoUrl} />}{delivery.imageUrl && <div className="rounded-2xl bg-white/70 p-4"><div className="mb-3 text-xs font-semibold uppercase text-muted-foreground">Image Guide</div><img src={delivery.imageUrl} alt="Delivery guide" className="max-h-[520px] w-full rounded-xl object-contain" /></div>}</div> : <div className="mt-4 rounded-xl border border-dashed border-border bg-white/60 p-4 text-sm text-muted-foreground">Delivery is approved. Refresh this page in a moment if details do not appear.</div>}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/70 p-4"><div className="text-xs font-semibold uppercase text-muted-foreground">{label}</div><div className="mt-2 flex items-center justify-between gap-3"><span className="break-all font-mono text-lg font-bold text-slate-900">{value || "Not provided"}</span>{value && <CopyButton value={value} />}</div></div>; }
function CopyButton({ value }: { value: string }) { return <button type="button" onClick={() => { navigator.clipboard.writeText(value); toast.success("Copied"); }} className="inline-flex items-center gap-1 rounded-lg bg-secondary px-2 py-1 text-xs"><Copy className="h-3 w-3" /> Copy</button>; }
function MediaVideo({ url }: { url: string }) { const yt = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([A-Za-z0-9_-]+)/)?.[1]; const src = yt ? `https://www.youtube.com/embed/${yt}` : url; return <div className="rounded-2xl bg-white/70 p-4"><div className="mb-3 text-xs font-semibold uppercase text-muted-foreground">Video Guide</div>{yt ? <iframe src={src} className="aspect-video w-full rounded-xl" allowFullScreen title="Delivery video" /> : <video src={src} controls className="max-h-[520px] w-full rounded-xl" />}</div>; }
function statusMeta(status: Order["status"]) { switch (status) { case "pending": return { Icon: Clock, title: "Order Pending", label: "Pending", message: "Waiting for admin approval. We'll update this page automatically.", iconBg: "bg-warning/15", iconColor: "text-warning", badge: "bg-warning/10 text-warning" }; case "approved": return { Icon: CheckCircle2, title: "Order Approved", label: "Approved", message: "Your delivery is ready below.", iconBg: "bg-primary/15", iconColor: "text-primary", badge: "bg-primary/10 text-primary" }; case "delivered": return { Icon: Truck, title: "Order Delivered", label: "Delivered", message: "Your delivery is ready below.", iconBg: "bg-success/15", iconColor: "text-success", badge: "bg-success/10 text-success" }; case "rejected": return { Icon: XCircle, title: "Order Rejected", label: "Rejected", message: "Your order was rejected. Contact support for help.", iconBg: "bg-destructive/15", iconColor: "text-destructive", badge: "bg-destructive/10 text-destructive" }; } }
function Row({ label, value, mono }: { label: string; value: string; mono?: boolean }) { return <div className="flex items-center justify-between gap-3"><span className="text-muted-foreground">{label}</span><span className={mono ? "break-all text-right font-mono font-semibold" : "text-right font-semibold"}>{value}</span></div>; }
