/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrderPendingRouteImport } from './routes/order-pending'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as OrderStatusOrderIdRouteImport } from './routes/order-status.$orderId'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPaymentSettingsRouteImport } from './routes/admin.payment-settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminOrdersRejectedRouteImport } from './routes/admin.orders.rejected'
import { Route as AdminOrdersPendingRouteImport } from './routes/admin.orders.pending'
import { Route as AdminOrdersDeliveredRouteImport } from './routes/admin.orders.delivered'
import { Route as AdminOrdersApprovedRouteImport } from './routes/admin.orders.approved'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPendingRoute = OrderPendingRouteImport.update({
  id: '/order-pending',
  path: '/order-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const OrderStatusOrderIdRoute = OrderStatusOrderIdRouteImport.update({
  id: '/order-status/$orderId',
  path: '/order-status/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentSettingsRoute = AdminPaymentSettingsRouteImport.update({
  id: '/payment-settings',
  path: '/payment-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRejectedRoute = AdminOrdersRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersPendingRoute = AdminOrdersPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersDeliveredRoute = AdminOrdersDeliveredRouteImport.update({
  id: '/delivered',
  path: '/delivered',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersApprovedRoute = AdminOrdersApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/order-pending': typeof OrderPendingRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/approved': typeof AdminOrdersApprovedRoute
  '/admin/orders/delivered': typeof AdminOrdersDeliveredRoute
  '/admin/orders/pending': typeof AdminOrdersPendingRoute
  '/admin/orders/rejected': typeof AdminOrdersRejectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/order-pending': typeof OrderPendingRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/approved': typeof AdminOrdersApprovedRoute
  '/admin/orders/delivered': typeof AdminOrdersDeliveredRoute
  '/admin/orders/pending': typeof AdminOrdersPendingRoute
  '/admin/orders/rejected': typeof AdminOrdersRejectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/order-pending': typeof OrderPendingRoute
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/stock': typeof AdminStockRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/approved': typeof AdminOrdersApprovedRoute
  '/admin/orders/delivered': typeof AdminOrdersDeliveredRoute
  '/admin/orders/pending': typeof AdminOrdersPendingRoute
  '/admin/orders/rejected': typeof AdminOrdersRejectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/order-pending'
    | '/products'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment-settings'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/users'
    | '/checkout/$productId'
    | '/order-status/$orderId'
    | '/products/$id'
    | '/admin/'
    | '/admin/orders/approved'
    | '/admin/orders/delivered'
    | '/admin/orders/pending'
    | '/admin/orders/rejected'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/order-pending'
    | '/products'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment-settings'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/users'
    | '/checkout/$productId'
    | '/order-status/$orderId'
    | '/products/$id'
    | '/admin'
    | '/admin/orders/approved'
    | '/admin/orders/delivered'
    | '/admin/orders/pending'
    | '/admin/orders/rejected'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/order-pending'
    | '/products'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment-settings'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/users'
    | '/checkout/$productId'
    | '/order-status/$orderId'
    | '/products/$id'
    | '/admin/'
    | '/admin/orders/approved'
    | '/admin/orders/delivered'
    | '/admin/orders/pending'
    | '/admin/orders/rejected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  OrderPendingRoute: typeof OrderPendingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  OrderStatusOrderIdRoute: typeof OrderStatusOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-pending': {
      id: '/order-pending'
      path: '/order-pending'
      fullPath: '/order-pending'
      preLoaderRoute: typeof OrderPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/order-status/$orderId': {
      id: '/order-status/$orderId'
      path: '/order-status/$orderId'
      fullPath: '/order-status/$orderId'
      preLoaderRoute: typeof OrderStatusOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-settings': {
      id: '/admin/payment-settings'
      path: '/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AdminPaymentSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/rejected': {
      id: '/admin/orders/rejected'
      path: '/rejected'
      fullPath: '/admin/orders/rejected'
      preLoaderRoute: typeof AdminOrdersRejectedRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/pending': {
      id: '/admin/orders/pending'
      path: '/pending'
      fullPath: '/admin/orders/pending'
      preLoaderRoute: typeof AdminOrdersPendingRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/delivered': {
      id: '/admin/orders/delivered'
      path: '/delivered'
      fullPath: '/admin/orders/delivered'
      preLoaderRoute: typeof AdminOrdersDeliveredRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/approved': {
      id: '/admin/orders/approved'
      path: '/approved'
      fullPath: '/admin/orders/approved'
      preLoaderRoute: typeof AdminOrdersApprovedRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersApprovedRoute: typeof AdminOrdersApprovedRoute
  AdminOrdersDeliveredRoute: typeof AdminOrdersDeliveredRoute
  AdminOrdersPendingRoute: typeof AdminOrdersPendingRoute
  AdminOrdersRejectedRoute: typeof AdminOrdersRejectedRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersApprovedRoute: AdminOrdersApprovedRoute,
  AdminOrdersDeliveredRoute: AdminOrdersDeliveredRoute,
  AdminOrdersPendingRoute: AdminOrdersPendingRoute,
  AdminOrdersRejectedRoute: AdminOrdersRejectedRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentSettingsRoute: typeof AdminPaymentSettingsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminStockRoute: typeof AdminStockRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentSettingsRoute: AdminPaymentSettingsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminStockRoute: AdminStockRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  OrderPendingRoute: OrderPendingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  OrderStatusOrderIdRoute: OrderStatusOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
