/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrderPendingRouteImport } from './routes/order-pending'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as TrackOrdersRouteImport } from './routes/track-orders'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMailTxtRouteImport } from './routes/admin.mail-txt'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentSettingsRouteImport } from './routes/admin.payment-settings'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPromoCodesRouteImport } from './routes/admin.promo-codes'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminStockRouteImport } from './routes/admin.stock'
import { Route as AdminTrackOrdersRouteImport } from './routes/admin.track-orders'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CheckoutProductIdRouteImport } from './routes/checkout.$productId'
import { Route as OrderStatusOrderIdRouteImport } from './routes/order-status.$orderId'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AdminCustomersCustomerKeyRouteImport } from './routes/admin.customers.$customerKey'
import { Route as AdminCustomersSearchRouteImport } from './routes/admin.customers.search'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersApprovedRouteImport } from './routes/admin.orders.approved'
import { Route as AdminOrdersCancelRouteImport } from './routes/admin.orders.cancel'
import { Route as AdminOrdersDeliveredRouteImport } from './routes/admin.orders.delivered'
import { Route as AdminOrdersPendingRouteImport } from './routes/admin.orders.pending'
import { Route as AdminOrdersRejectedRouteImport } from './routes/admin.orders.rejected'
import { Route as AdminResellersIdRouteImport } from './routes/admin.resellers.$id'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPendingRoute = OrderPendingRouteImport.update({
  id: '/order-pending',
  path: '/order-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrdersRoute = TrackOrdersRouteImport.update({
  id: '/track-orders',
  path: '/track-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMailTxtRoute = AdminMailTxtRouteImport.update({
  id: '/mail-txt',
  path: '/mail-txt',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentSettingsRoute = AdminPaymentSettingsRouteImport.update({
  id: '/payment-settings',
  path: '/payment-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoCodesRoute = AdminPromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockRoute = AdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackOrdersRoute = AdminTrackOrdersRouteImport.update({
  id: '/track-orders',
  path: '/track-orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutProductIdRoute = CheckoutProductIdRouteImport.update({
  id: '/checkout/$productId',
  path: '/checkout/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusOrderIdRoute = OrderStatusOrderIdRouteImport.update({
  id: '/order-status/$orderId',
  path: '/order-status/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const AdminCustomersCustomerKeyRoute =
  AdminCustomersCustomerKeyRouteImport.update({
    id: '/$customerKey',
    path: '/$customerKey',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersSearchRoute = AdminCustomersSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersApprovedRoute = AdminOrdersApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersCancelRoute = AdminOrdersCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersDeliveredRoute = AdminOrdersDeliveredRouteImport.update({
  id: '/delivered',
  path: '/delivered',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersPendingRoute = AdminOrdersPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersRejectedRoute = AdminOrdersRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminResellersIdRoute = AdminResellersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminResellersRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/order-pending': typeof OrderPendingRoute
  '/products': typeof ProductsRouteWithChildren
  '/track-orders': typeof TrackOrdersRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/mail-txt': typeof AdminMailTxtRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/resellers': typeof AdminResellersRouteWithChildren
  '/admin/stock': typeof AdminStockRoute
  '/admin/track-orders': typeof AdminTrackOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerKey': typeof AdminCustomersCustomerKeyRoute
  '/admin/customers/search': typeof AdminCustomersSearchRoute
  '/admin/orders/approved': typeof AdminOrdersApprovedRoute
  '/admin/orders/cancel': typeof AdminOrdersCancelRoute
  '/admin/orders/delivered': typeof AdminOrdersDeliveredRoute
  '/admin/orders/pending': typeof AdminOrdersPendingRoute
  '/admin/orders/rejected': typeof AdminOrdersRejectedRoute
  '/admin/resellers/$id': typeof AdminResellersIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/order-pending': typeof OrderPendingRoute
  '/products': typeof ProductsRouteWithChildren
  '/track-orders': typeof TrackOrdersRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/mail-txt': typeof AdminMailTxtRoute
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/resellers': typeof AdminResellersRouteWithChildren
  '/admin/stock': typeof AdminStockRoute
  '/admin/track-orders': typeof AdminTrackOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$customerKey': typeof AdminCustomersCustomerKeyRoute
  '/admin/customers/search': typeof AdminCustomersSearchRoute
  '/admin/orders/approved': typeof AdminOrdersApprovedRoute
  '/admin/orders/cancel': typeof AdminOrdersCancelRoute
  '/admin/orders/delivered': typeof AdminOrdersDeliveredRoute
  '/admin/orders/pending': typeof AdminOrdersPendingRoute
  '/admin/orders/rejected': typeof AdminOrdersRejectedRoute
  '/admin/resellers/$id': typeof AdminResellersIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/order-pending': typeof OrderPendingRoute
  '/products': typeof ProductsRouteWithChildren
  '/track-orders': typeof TrackOrdersRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/mail-txt': typeof AdminMailTxtRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payment-settings': typeof AdminPaymentSettingsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promo-codes': typeof AdminPromoCodesRoute
  '/admin/resellers': typeof AdminResellersRouteWithChildren
  '/admin/stock': typeof AdminStockRoute
  '/admin/track-orders': typeof AdminTrackOrdersRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$productId': typeof CheckoutProductIdRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerKey': typeof AdminCustomersCustomerKeyRoute
  '/admin/customers/search': typeof AdminCustomersSearchRoute
  '/admin/orders/approved': typeof AdminOrdersApprovedRoute
  '/admin/orders/cancel': typeof AdminOrdersCancelRoute
  '/admin/orders/delivered': typeof AdminOrdersDeliveredRoute
  '/admin/orders/pending': typeof AdminOrdersPendingRoute
  '/admin/orders/rejected': typeof AdminOrdersRejectedRoute
  '/admin/resellers/$id': typeof AdminResellersIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/order-pending'
    | '/products'
    | '/track-orders'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/mail-txt'
    | '/admin/orders'
    | '/admin/payment-settings'
    | '/admin/products'
    | '/admin/promo-codes'
    | '/admin/resellers'
    | '/admin/stock'
    | '/admin/track-orders'
    | '/admin/users'
    | '/checkout/$productId'
    | '/order-status/$orderId'
    | '/products/$id'
    | '/admin/'
    | '/admin/customers/$customerKey'
    | '/admin/customers/search'
    | '/admin/orders/approved'
    | '/admin/orders/cancel'
    | '/admin/orders/delivered'
    | '/admin/orders/pending'
    | '/admin/orders/rejected'
    | '/admin/resellers/$id'
    | '/auth/google/callback'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/order-pending'
    | '/products'
    | '/track-orders'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/mail-txt'
    | '/admin/payment-settings'
    | '/admin/products'
    | '/admin/promo-codes'
    | '/admin/resellers'
    | '/admin/stock'
    | '/admin/track-orders'
    | '/admin/users'
    | '/checkout/$productId'
    | '/order-status/$orderId'
    | '/products/$id'
    | '/admin'
    | '/admin/customers/$customerKey'
    | '/admin/customers/search'
    | '/admin/orders/approved'
    | '/admin/orders/cancel'
    | '/admin/orders/delivered'
    | '/admin/orders/pending'
    | '/admin/orders/rejected'
    | '/admin/resellers/$id'
    | '/auth/google/callback'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/order-pending'
    | '/products'
    | '/track-orders'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/mail-txt'
    | '/admin/orders'
    | '/admin/payment-settings'
    | '/admin/products'
    | '/admin/promo-codes'
    | '/admin/resellers'
    | '/admin/stock'
    | '/admin/track-orders'
    | '/admin/users'
    | '/checkout/$productId'
    | '/order-status/$orderId'
    | '/products/$id'
    | '/admin/'
    | '/admin/customers/$customerKey'
    | '/admin/customers/search'
    | '/admin/orders/approved'
    | '/admin/orders/cancel'
    | '/admin/orders/delivered'
    | '/admin/orders/pending'
    | '/admin/orders/rejected'
    | '/admin/resellers/$id'
    | '/auth/google/callback'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  OrderPendingRoute: typeof OrderPendingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  TrackOrdersRoute: typeof TrackOrdersRoute
  CheckoutProductIdRoute: typeof CheckoutProductIdRoute
  OrderStatusOrderIdRoute: typeof OrderStatusOrderIdRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-pending': {
      id: '/order-pending'
      path: '/order-pending'
      fullPath: '/order-pending'
      preLoaderRoute: typeof OrderPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-orders': {
      id: '/track-orders'
      path: '/track-orders'
      fullPath: '/track-orders'
      preLoaderRoute: typeof TrackOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mail-txt': {
      id: '/admin/mail-txt'
      path: '/mail-txt'
      fullPath: '/admin/mail-txt'
      preLoaderRoute: typeof AdminMailTxtRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payment-settings': {
      id: '/admin/payment-settings'
      path: '/payment-settings'
      fullPath: '/admin/payment-settings'
      preLoaderRoute: typeof AdminPaymentSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo-codes': {
      id: '/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminPromoCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock': {
      id: '/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AdminStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/track-orders': {
      id: '/admin/track-orders'
      path: '/track-orders'
      fullPath: '/admin/track-orders'
      preLoaderRoute: typeof AdminTrackOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/$productId': {
      id: '/checkout/$productId'
      path: '/checkout/$productId'
      fullPath: '/checkout/$productId'
      preLoaderRoute: typeof CheckoutProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status/$orderId': {
      id: '/order-status/$orderId'
      path: '/order-status/$orderId'
      fullPath: '/order-status/$orderId'
      preLoaderRoute: typeof OrderStatusOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/admin/customers/$customerKey': {
      id: '/admin/customers/$customerKey'
      path: '/$customerKey'
      fullPath: '/admin/customers/$customerKey'
      preLoaderRoute: typeof AdminCustomersCustomerKeyRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/search': {
      id: '/admin/customers/search'
      path: '/search'
      fullPath: '/admin/customers/search'
      preLoaderRoute: typeof AdminCustomersSearchRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/approved': {
      id: '/admin/orders/approved'
      path: '/approved'
      fullPath: '/admin/orders/approved'
      preLoaderRoute: typeof AdminOrdersApprovedRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/cancel': {
      id: '/admin/orders/cancel'
      path: '/cancel'
      fullPath: '/admin/orders/cancel'
      preLoaderRoute: typeof AdminOrdersCancelRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/delivered': {
      id: '/admin/orders/delivered'
      path: '/delivered'
      fullPath: '/admin/orders/delivered'
      preLoaderRoute: typeof AdminOrdersDeliveredRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/pending': {
      id: '/admin/orders/pending'
      path: '/pending'
      fullPath: '/admin/orders/pending'
      preLoaderRoute: typeof AdminOrdersPendingRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/rejected': {
      id: '/admin/orders/rejected'
      path: '/rejected'
      fullPath: '/admin/orders/rejected'
      preLoaderRoute: typeof AdminOrdersRejectedRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/resellers/$id': {
      id: '/admin/resellers/$id'
      path: '/$id'
      fullPath: '/admin/resellers/$id'
      preLoaderRoute: typeof AdminResellersIdRouteImport
      parentRoute: typeof AdminResellersRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerKeyRoute: typeof AdminCustomersCustomerKeyRoute
  AdminCustomersSearchRoute: typeof AdminCustomersSearchRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerKeyRoute: AdminCustomersCustomerKeyRoute,
  AdminCustomersSearchRoute: AdminCustomersSearchRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersApprovedRoute: typeof AdminOrdersApprovedRoute
  AdminOrdersCancelRoute: typeof AdminOrdersCancelRoute
  AdminOrdersDeliveredRoute: typeof AdminOrdersDeliveredRoute
  AdminOrdersPendingRoute: typeof AdminOrdersPendingRoute
  AdminOrdersRejectedRoute: typeof AdminOrdersRejectedRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersApprovedRoute: AdminOrdersApprovedRoute,
  AdminOrdersCancelRoute: AdminOrdersCancelRoute,
  AdminOrdersDeliveredRoute: AdminOrdersDeliveredRoute,
  AdminOrdersPendingRoute: AdminOrdersPendingRoute,
  AdminOrdersRejectedRoute: AdminOrdersRejectedRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminResellersRouteChildren {
  AdminResellersIdRoute: typeof AdminResellersIdRoute
}

const AdminResellersRouteChildren: AdminResellersRouteChildren = {
  AdminResellersIdRoute: AdminResellersIdRoute,
}

const AdminResellersRouteWithChildren = AdminResellersRoute._addFileChildren(
  AdminResellersRouteChildren,
)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMailTxtRoute: typeof AdminMailTxtRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentSettingsRoute: typeof AdminPaymentSettingsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromoCodesRoute: typeof AdminPromoCodesRoute
  AdminResellersRoute: typeof AdminResellersRouteWithChildren
  AdminStockRoute: typeof AdminStockRoute
  AdminTrackOrdersRoute: typeof AdminTrackOrdersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMailTxtRoute: AdminMailTxtRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentSettingsRoute: AdminPaymentSettingsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromoCodesRoute: AdminPromoCodesRoute,
  AdminResellersRoute: AdminResellersRouteWithChildren,
  AdminStockRoute: AdminStockRoute,
  AdminTrackOrdersRoute: AdminTrackOrdersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  OrderPendingRoute: OrderPendingRoute,
  ProductsRoute: ProductsRouteWithChildren,
  TrackOrdersRoute: TrackOrdersRoute,
  CheckoutProductIdRoute: CheckoutProductIdRoute,
  OrderStatusOrderIdRoute: OrderStatusOrderIdRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
